# Generated by Django 3.1.13 on 2021-08-28 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'usuarios',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('fechaNacimiento', models.DateField(blank=True, db_column='fecha_nacimiento', null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extraInfo', serialize=False, to='api.usuario')),
            ],
            options={
                'db_table': 'informacion_extra',
            },
        ),
    ]
